language: node_js
node_js:
- stable
addons:
  sonarcloud:
    organization: theyoxy
    token:
      secure: JW0uZiTI/Uko/G2DAOwPRQ67IXnRmZHE42VnM7noc05c6NIzUbAxxtYcJOXbzsENDB8oOhgNPhLQbBzQhFoF8OOBqWBTQNKy8DmhFlqKas4LdZbmyIUZm4O6bp6DazncXN5rZBKkDDT9aOWLreWGUFtz+t1Gd0RDtgKIk3r+uPfh1v7Pe9EqYFGOLpATqfvf9CC4onmCsBzavZxhd5fOKQelF0GvGFOsCwUFkq/q3Z+WBv7U4xd+7IrOPSnv3Z6xIr6bAzmFwn8/ZcRqiisX1xbKlAWecXrdJ6JJzig16vtPAJr88KWzi9zxCpBhN97xgEiKnuzpge4HSEBGhmplYQb/ISXtHCil+uwfaHRxkS+Sf4K2me0gIqRggoWQ+XChLOWwJ2f0IAtqJqEBUklR/zA1nRjxH2B+6C49+jdXVWbR01NHy17joBwKG6tsde485oaHkYHo31aRDkznm3zu69OiFqtlOsd4IESt2CSmSxlhs2q8CcxAYHvqL4y+1ZThj7oTx3ZKN0GnUieICrhlKiM/meYOoYbPJnXhh0ERSPwPQAtGF6dIwxsWf4NPvOOuZjgMNlmfbbTQlNBeE+KJhqj8s1YOgC+Coj3rYOx3htjBjw9ukz+N3Zid61mj5X9I1RsQ6uYBeba1fr5uGEhhKM+XzmIWxymGZEo/hHMzOWE=
script:
- yarn test
- sonar-scanner
- yarn version --prepatch
- git push --mirror
env:
  global:
  - secure: DNxd5WOAY5QP+GoYNtvDXGsvFVdTpxwhK1PAE34oU7OYtGchUqR8JFN2K8mc8pmqAunQRxe8k9423PjjjHMYMwc0mo/c9TJqoZOL/lYFkuK6TjJ49hjuyu5OoTx2BDk+saTAR3J+mRc4TfG1ksRZWt7ivLMVvUCPIGXPp0BBjEepQVujzEZ6Ws2w5oSSBxFSCP+l8PthA72rVXGc2oyhW6cb6XV091A6dprAIJUHJRe/HwjNj9nBvA61hR7bHjMTmvWJFESS3oRGzKTXqHkIRANC1e+forVdfgCiP3Atn2C7kkSh0n9bAP9yMCJS/evTVkl3P1KAbUZGYFIL2ol58a5ReYsPrvIVOGmFkz4RjZ9GA4lv96zq5tvrqTmJvthA5VselhOFd8XT5I1G8ae+v40pQlkwsFF4cl1uKP89gSJt19y/t3OIgvazixNhuDXT6jFtOybfXWs8fC9eeuaKClaRSOV+Ujgi4MxB3FLbzv+E3wOMbdH+1PasL9vk8L2qGd27AnsUZNKRfG0vPdqL5Ty7kMM/9MInry+qOu+yqr49umpIPxZ5vS0A3QQEXFnP2vVXp/vNvh7RHW/uPvh+mr//qhOhu2DOALfa6ky5UuF72OnqaRKNJ9nsjYmua9HvDADhqUGJgc9BExDH6rZrpdQVZW3MLm9cfZIbKQTk1eE=
  