language: node_js
node_js:
  - stable
addons:
  sonarcloud:
    organization: theyoxy
    token:
      secure: JW0uZiTI/Uko/G2DAOwPRQ67IXnRmZHE42VnM7noc05c6NIzUbAxxtYcJOXbzsENDB8oOhgNPhLQbBzQhFoF8OOBqWBTQNKy8DmhFlqKas4LdZbmyIUZm4O6bp6DazncXN5rZBKkDDT9aOWLreWGUFtz+t1Gd0RDtgKIk3r+uPfh1v7Pe9EqYFGOLpATqfvf9CC4onmCsBzavZxhd5fOKQelF0GvGFOsCwUFkq/q3Z+WBv7U4xd+7IrOPSnv3Z6xIr6bAzmFwn8/ZcRqiisX1xbKlAWecXrdJ6JJzig16vtPAJr88KWzi9zxCpBhN97xgEiKnuzpge4HSEBGhmplYQb/ISXtHCil+uwfaHRxkS+Sf4K2me0gIqRggoWQ+XChLOWwJ2f0IAtqJqEBUklR/zA1nRjxH2B+6C49+jdXVWbR01NHy17joBwKG6tsde485oaHkYHo31aRDkznm3zu69OiFqtlOsd4IESt2CSmSxlhs2q8CcxAYHvqL4y+1ZThj7oTx3ZKN0GnUieICrhlKiM/meYOoYbPJnXhh0ERSPwPQAtGF6dIwxsWf4NPvOOuZjgMNlmfbbTQlNBeE+KJhqj8s1YOgC+Coj3rYOx3htjBjw9ukz+N3Zid61mj5X9I1RsQ6uYBeba1fr5uGEhhKM+XzmIWxymGZEo/hHMzOWE=
script:
  - yarn test
  - 'sonar-scanner -X -Dsonar.projectVersion=$(cat package.json | grep version | head -1 | awk -F: ''{ print $2 }'' | sed ''s/[",]//g'' | tr -d ''[[:space:]]'')'
after_deploy:
  - yarn version --prerelease
  - git push --mirror
notifications:
  email:
    on_success: change
    on_failure: change
